// products/amliq/web/src/components/layout/MobileHeader.tsx
import { Menu } from 'lucide-react'
import { NotificationBell } from './NotificationBell'
import Logo from '../brand/Logo'

interface MobileHeaderProps {
  onMenuToggle: () => void
}

export function MobileHeader({ onMenuToggle }: MobileHeaderProps) {
  return (
    <header className="md:hidden sticky top-0 z-40 h-14 flex items-center justify-between px-4"
      style={{
        background: 'var(--dash-nav-bg)',
        backdropFilter: 'blur(40px) saturate(200%)',
        WebkitBackdropFilter: 'blur(40px) saturate(200%)',
        borderBottom: '0.5px solid var(--dash-border)',
      }}>
      <button type="button" onClick={onMenuToggle}
        className="w-9 h-9 flex items-center justify-center rounded-xl
          transition-all cursor-pointer active:scale-90"
        style={{ color: 'var(--dash-text-secondary)' }}>
        <Menu className="w-5 h-5" />
      </button>

      <Logo size={22} />

      <NotificationBell />
    </header>
  )
}

// products/tenantiq/apps/web/src/lib/components/MobileHeader.svelte
<script lang="ts">
	import { Menu } from 'lucide-svelte';
	import NotificationBell from '$components/NotificationBell.svelte';
	import ThemeToggle from '$components/ThemeToggle.svelte';

	interface Props {
		onToggleSidebar: () => void;
	}

	let { onToggleSidebar }: Props = $props();
</script>

<header class="mobile-header flex h-14 items-center justify-between border-b border-[var(--color-border)] bg-[var(--color-surface-glass)] px-4 backdrop-blur-xl md:hidden">
	<div class="flex items-center gap-2.5">
		<button
			type="button"
			onclick={onToggleSidebar}
			aria-label="Open navigation menu"
			class="flex h-10 w-10 cursor-pointer items-center justify-center rounded-xl text-[var(--color-text-secondary)] transition-all hover:bg-[var(--color-primary-muted)] hover:text-[var(--color-primary)]"
		>
			<Menu size={20} strokeWidth={2} />
		</button>
		<div class="flex items-center gap-1.5">
			<img src="/brand/app-icon.png" alt="" aria-hidden="true" width="24" height="24" class="h-6 w-6 rounded-lg" />
			<span class="text-[15px] font-bold tracking-tight text-[var(--color-text)]">TenantIQ</span>
		</div>
	</div>
	<div class="flex items-center gap-1.5">
		<ThemeToggle />
		<NotificationBell />
	</div>
</header>
