// products/tenantiq/web/src/lib/components/ThemeToggle.svelte
<script lang="ts">
	import { theme, type ThemeMode } from '$stores/theme';
	import { Sun, Moon, Monitor } from 'lucide-svelte';

	const options: { mode: ThemeMode; icon: typeof Sun; label: string }[] = [
		{ mode: 'light', icon: Sun, label: 'Light' },
		{ mode: 'dark', icon: Moon, label: 'Dark' },
		{ mode: 'auto', icon: Monitor, label: 'Auto' },
	];
</script>

<div class="flex items-center rounded-lg border border-[var(--color-border)] bg-[var(--color-surface)] p-0.5">
	{#each options as opt}
		<button
			onclick={() => theme.setTheme(opt.mode)}
			class="flex h-9 w-9 items-center justify-center rounded-md transition-all duration-200
				{$theme === opt.mode
					? 'bg-[var(--color-primary)] text-white shadow-sm'
					: 'text-[var(--color-text-tertiary)] hover:text-[var(--color-text-secondary)]'}"
			title={opt.label}
			aria-label="{opt.label} theme"
		>
			<opt.icon size={16} />
		</button>
	{/each}
</div>

// products/amliq/web/src/components/ui/ThemeToggle.tsx
import { Sun, Moon, Sparkles } from 'lucide-react'
import { useTheme } from '../../context/ThemeContext'

export function ThemeToggle() {
  const { theme, cycle } = useTheme()

  const icons = {
    light: <Moon className="w-4 h-4" style={{ color: 'var(--dash-text-secondary)' }} />,
    dark: <Sun className="w-4 h-4" style={{ color: '#C9A96E' }} />,
    midnight: <Sun className="w-4 h-4" style={{ color: '#C9A96E' }} />,
    marketing: <Sparkles className="w-4 h-4" style={{ color: '#C9A96E' }} />,
  }

  const labels = {
    light: 'Switch to dark mode',
    dark: 'Switch to midnight mode',
    midnight: 'Switch to marketing theme',
    marketing: 'Switch to light mode',
  }

  return (
    <button
      type="button"
      onClick={cycle}
      className="w-9 h-9 flex items-center justify-center rounded-xl
        hover:bg-[var(--dash-surface-hover)] border border-[var(--dash-border)]
        transition-all duration-200 cursor-pointer active:scale-90"
      style={{ background: 'var(--dash-surface)' }}
      aria-label={labels[theme]}
    >
      {icons[theme]}
    </button>
  )
}
