// products/opensyber/apps/web/src/app/dashboard/executive/ScoreRing.tsx
'use client';

interface ScoreRingProps {
  score: number;
  grade: string;
  delta: number;
  riskLevel: string;
}

function getGradeColor(grade: string): string {
  if (grade.startsWith('A')) return 'text-green-400';
  if (grade.startsWith('B')) return 'text-info';
  if (grade.startsWith('C')) return 'text-amber-400';
  return 'text-red-400';
}

function getRiskColor(level: string): string {
  const colors: Record<string, string> = {
    Excellent: 'bg-green-500/10 text-green-400',
    Low: 'bg-green-500/10 text-green-400',
    Medium: 'bg-amber-500/10 text-amber-400',
    High: 'bg-red-500/10 text-red-400',
    Critical: 'bg-red-500/10 text-red-400',
  };
  return colors[level] ?? 'bg-neutral-800 text-neutral-400';
}

function getStrokeColor(score: number): string {
  if (score >= 90) return '#22c55e';
  if (score >= 70) return '#3b82f6';
  if (score >= 50) return '#f59e0b';
  return '#ef4444';
}

export function ScoreRing({ score, grade, delta, riskLevel }: ScoreRingProps) {
  const radius = 80;
  const circumference = 2 * Math.PI * radius;
  const offset = circumference - (score / 100) * circumference;
  const strokeColor = getStrokeColor(score);

  return (
    <div className="rounded-xl border border-neutral-800 bg-neutral-900/30 p-8">
      <div className="flex flex-col items-center gap-6 sm:flex-row sm:items-center sm:gap-12">
        <div className="relative flex-shrink-0">
          <svg width="200" height="200" viewBox="0 0 200 200" data-testid="score-ring-svg">
            <circle cx="100" cy="100" r={radius} fill="none" stroke="#262626" strokeWidth="12" />
            <circle
              cx="100" cy="100" r={radius} fill="none"
              stroke={strokeColor} strokeWidth="12" strokeLinecap="round"
              strokeDasharray={circumference} strokeDashoffset={offset}
              transform="rotate(-90 100 100)"
              className="transition-all duration-1000"
            />
          </svg>
          <div className="absolute inset-0 flex flex-col items-center justify-center">
            <span className="text-5xl font-bold">{score}</span>
            <span className={`text-2xl font-semibold ${getGradeColor(grade)}`}>{grade}</span>
          </div>
        </div>
        <div className="flex flex-col items-center sm:items-start gap-3">
          <h2 className="text-lg font-medium text-neutral-400">Security Score</h2>
          <div className="flex items-center gap-2">
            {delta > 0 ? (
              <span className="text-green-400 text-sm font-medium flex items-center gap-1">
                <ArrowUp /> +{delta} vs last month
              </span>
            ) : delta < 0 ? (
              <span className="text-red-400 text-sm font-medium flex items-center gap-1">
                <ArrowDown /> {delta} vs last month
              </span>
            ) : (
              <span className="text-neutral-400 text-sm">No change vs last month</span>
            )}
          </div>
          <span className={`inline-flex items-center rounded-full px-3 py-1 text-xs font-medium ${getRiskColor(riskLevel)}`}>
            {riskLevel} Risk
          </span>
        </div>
      </div>
    </div>
  );
}

function ArrowUp() {
  return (
    <svg width="14" height="14" viewBox="0 0 14 14" fill="none">
      <path d="M7 2L12 8H2L7 2Z" fill="currentColor" />
    </svg>
  );
}

function ArrowDown() {
  return (
    <svg width="14" height="14" viewBox="0 0 14 14" fill="none">
      <path d="M7 12L2 6H12L7 12Z" fill="currentColor" />
    </svg>
  );
}

// products/tenantiq/web/src/lib/components/ScoreRing.svelte
<script lang="ts">
	interface Props {
		score: number;
		size?: number;
		strokeWidth?: number;
		label?: string;
	}

	let { score, size = 120, strokeWidth = 8, label = 'Score' }: Props = $props();

	const radius = $derived((size - strokeWidth) / 2);
	const circumference = $derived(2 * Math.PI * radius);
	const offset = $derived(circumference - (score / 100) * circumference);

	const gradientId = `score-gradient-${Math.random().toString(36).slice(2, 8)}`;

	// Rich gradient colors based on score
	const gradientStops = $derived(
		score >= 70
			? { start: '#22c55e', end: '#15803d' }
			: score >= 40
				? { start: '#f59e0b', end: '#d97706' }
				: { start: '#ef4444', end: '#dc2626' }
	);
</script>

<div class="relative inline-flex items-center justify-center" style="width: {size}px; height: {size}px;">
	<svg width={size} height={size} class="-rotate-90">
		<defs>
			<linearGradient id={gradientId} x1="0%" y1="0%" x2="100%" y2="100%">
				<stop offset="0%" stop-color={gradientStops.start} />
				<stop offset="100%" stop-color={gradientStops.end} />
			</linearGradient>
			<!-- Soft glow filter -->
			<filter id="{gradientId}-glow">
				<feGaussianBlur stdDeviation="3" result="blur" />
				<feMerge>
					<feMergeNode in="blur" />
					<feMergeNode in="SourceGraphic" />
				</feMerge>
			</filter>
		</defs>
		<!-- Background ring — subtle -->
		<circle
			cx={size / 2} cy={size / 2} r={radius}
			fill="none"
			stroke="var(--color-border-subtle)"
			stroke-width={strokeWidth}
			opacity="0.6"
		/>
		<!-- Score ring — gradient with glow -->
		<circle
			cx={size / 2} cy={size / 2} r={radius}
			fill="none"
			stroke="url(#{gradientId})"
			stroke-width={strokeWidth}
			stroke-linecap="round"
			stroke-dasharray={circumference}
			stroke-dashoffset={offset}
			class="animate-draw-ring"
			style="--ring-circumference: {circumference}"
			filter="url(#{gradientId}-glow)"
		/>
	</svg>
	<div class="absolute inset-0 flex flex-col items-center justify-center">
		<span class="text-[28px] font-extrabold tracking-tighter text-[var(--color-text)]">{score}</span>
		<span class="text-[10px] font-medium tracking-wide text-[var(--color-text-tertiary)]">{label}</span>
	</div>
</div>
