// products/tenantiq/web/src/lib/components/ScoreRing.svelte
<script lang="ts">
	interface Props {
		score: number;
		size?: number;
		strokeWidth?: number;
		label?: string;
	}

	let { score, size = 120, strokeWidth = 8, label = 'Score' }: Props = $props();

	const radius = $derived((size - strokeWidth) / 2);
	const circumference = $derived(2 * Math.PI * radius);
	const offset = $derived(circumference - (score / 100) * circumference);

	const gradientId = `score-gradient-${Math.random().toString(36).slice(2, 8)}`;

	// Rich gradient colors based on score
	const gradientStops = $derived(
		score >= 70
			? { start: '#22c55e', end: '#15803d' }
			: score >= 40
				? { start: '#f59e0b', end: '#d97706' }
				: { start: '#ef4444', end: '#dc2626' }
	);
</script>

<div class="relative inline-flex items-center justify-center" style="width: {size}px; height: {size}px;">
	<svg width={size} height={size} class="-rotate-90">
		<defs>
			<linearGradient id={gradientId} x1="0%" y1="0%" x2="100%" y2="100%">
				<stop offset="0%" stop-color={gradientStops.start} />
				<stop offset="100%" stop-color={gradientStops.end} />
			</linearGradient>
			<!-- Soft glow filter -->
			<filter id="{gradientId}-glow">
				<feGaussianBlur stdDeviation="3" result="blur" />
				<feMerge>
					<feMergeNode in="blur" />
					<feMergeNode in="SourceGraphic" />
				</feMerge>
			</filter>
		</defs>
		<!-- Background ring — subtle -->
		<circle
			cx={size / 2} cy={size / 2} r={radius}
			fill="none"
			stroke="var(--color-border-subtle)"
			stroke-width={strokeWidth}
			opacity="0.6"
		/>
		<!-- Score ring — gradient with glow -->
		<circle
			cx={size / 2} cy={size / 2} r={radius}
			fill="none"
			stroke="url(#{gradientId})"
			stroke-width={strokeWidth}
			stroke-linecap="round"
			stroke-dasharray={circumference}
			stroke-dashoffset={offset}
			class="animate-draw-ring"
			style="--ring-circumference: {circumference}"
			filter="url(#{gradientId}-glow)"
		/>
	</svg>
	<div class="absolute inset-0 flex flex-col items-center justify-center">
		<span class="text-[28px] font-extrabold tracking-tighter text-[var(--color-text)]">{score}</span>
		<span class="text-[10px] font-medium tracking-wide text-[var(--color-text-tertiary)]">{label}</span>
	</div>
</div>

// products/sdlc-cc/platform/ai-seo-optimizer/components/ScoreRing.tsx
import { memo } from 'react';
import { motion } from 'framer-motion';

interface ScoreRingProps {
  score: number;
  size?: number;
  label?: string;
}

const getScoreColor = (score: number) => {
  if (score >= 80) return { stroke: '#10B981', bg: 'rgba(16, 185, 129, 0.08)' };
  if (score >= 50) return { stroke: '#F59E0B', bg: 'rgba(245, 158, 11, 0.08)' };
  return { stroke: '#EF4444', bg: 'rgba(239, 68, 68, 0.08)' };
};

export const ScoreRing: React.FC<ScoreRingProps> = memo(({ score, size = 120, label }) => {
  const { stroke, bg } = getScoreColor(score);
  const radius = (size - 12) / 2;
  const circumference = 2 * Math.PI * radius;
  const offset = circumference - (score / 100) * circumference;
  const center = size / 2;

  return (
    <div className="flex flex-col items-center gap-2">
      <div className="relative" style={{ width: size, height: size }}>
        <svg width={size} height={size} className="score-ring">
          <circle
            cx={center} cy={center} r={radius}
            fill={bg}
            stroke="#E2E8F0"
            strokeWidth="6"
          />
          <motion.circle
            cx={center} cy={center} r={radius}
            fill="none"
            stroke={stroke}
            strokeWidth="6"
            strokeLinecap="round"
            strokeDasharray={circumference}
            initial={{ strokeDashoffset: circumference }}
            whileInView={{ strokeDashoffset: offset }}
            viewport={{ once: true }}
            transition={{ duration: 1.2, ease: 'easeOut', delay: 0.3 }}
          />
        </svg>
        <div className="absolute inset-0 flex items-center justify-center rotate-0">
          <span className="text-2xl font-bold text-slate-900">{score}</span>
        </div>
      </div>
      {label && (
        <span className="text-xs font-medium text-slate-500 uppercase tracking-wide">
          {label}
        </span>
      )}
    </div>
  );
});

ScoreRing.displayName = 'ScoreRing';
