// oss/tokenforge/apps/dashboard/src/routes/apps/[id]/users/+page.svelte
<script lang="ts">
  import type { PageData } from './$types.js';
  let { data }: { data: PageData } = $props();
</script>

<section class="space-y-4">
  <header>
    <a href="/apps/{data.app.id}" class="text-xs text-zinc-500 hover:text-zinc-300">&larr; {data.app.name}</a>
    <h1 class="mt-1 text-2xl font-semibold tracking-tight">Users</h1>
    <p class="mt-1 text-sm text-zinc-400">
      Subjects derived from session bindings. {data.app.mode === 'workforce'
        ? 'Workforce mode: synced from your IdP via OIDC `sub`.'
        : 'Customer mode: subjects are your end-users.'}
    </p>
  </header>

  {#if data.subjects.length === 0}
    <p class="rounded border border-zinc-800 bg-zinc-900/30 p-6 text-center text-sm text-zinc-400">
      No subjects yet. They appear once a session is bound for the app.
    </p>
  {:else}
    <div class="overflow-x-auto rounded border border-zinc-800">
      <table class="w-full text-sm">
        <thead class="bg-zinc-900/50 text-zinc-400">
          <tr>
            <th class="px-3 py-2 text-left font-medium">Subject</th>
            <th class="px-3 py-2 text-left font-medium">Active</th>
            <th class="px-3 py-2 text-left font-medium">First seen</th>
            <th class="px-3 py-2 text-left font-medium">Last seen</th>
          </tr>
        </thead>
        <tbody class="divide-y divide-zinc-800 bg-zinc-950/40">
          {#each data.subjects as s (s.externalSubject)}
            <tr class="text-zinc-300">
              <td class="px-3 py-2"><code class="text-zinc-200">{s.externalSubject}</code></td>
              <td class="px-3 py-2 tabular-nums">{s.activeSessions}</td>
              <td class="px-3 py-2 text-zinc-500 tabular-nums">{s.firstSeenAt.slice(0, 19).replace('T', ' ')}</td>
              <td class="px-3 py-2 text-zinc-500 tabular-nums">{s.lastSeenAt.slice(0, 19).replace('T', ' ')}</td>
            </tr>
          {/each}
        </tbody>
      </table>
    </div>
  {/if}
</section>

// products/opensyber/apps/tokenforge-web/src/app/dashboard/workforce/users/page.tsx
'use client';

import { useCallback, useState } from 'react';
import { Users, Download } from 'lucide-react';
import { useApi } from '@/lib/use-api';
import { fetchSubjects, type Subject } from '@/lib/tokenforge-api-workforce';

export default function WorkforceUsersPage(): React.ReactElement {
  const fetcher = useCallback(
    (token: string, signal: AbortSignal) => fetchSubjects(token, signal),
    [],
  );
  const { data: subjects, loading } = useApi<Subject[]>(fetcher);
  const [search, setSearch] = useState('');

  const filtered = (subjects ?? []).filter((s) => {
    const q = search.toLowerCase();
    return (
      (s.email?.toLowerCase().includes(q) ?? false) ||
      (s.name?.toLowerCase().includes(q) ?? false) ||
      s.externalSubject.toLowerCase().includes(q)
    );
  });

  function exportCsv(): void {
    const rows = [
      ['ID', 'Email', 'Name', 'External ID', 'First Seen', 'Last Seen'],
      ...filtered.map((s) => [
        s.id, s.email ?? '', s.name ?? '', s.externalSubject, s.firstSeenAt, s.lastSeenAt,
      ]),
    ];
    const csv = rows.map((r) => r.map((c) => `"${c}"`).join(',')).join('\n');
    const blob = new Blob([csv], { type: 'text/csv' });
    const a = document.createElement('a');
    a.href = URL.createObjectURL(blob);
    a.download = 'workforce-users.csv';
    a.click();
  }

  return (
    <div>
      <div className="mb-8 flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold">Workforce Users</h1>
          <p className="mt-1 text-sm text-text-secondary">
            Users authenticated via OIDC IdP and bound with DBSC
          </p>
        </div>
        <button
          onClick={exportCsv}
          disabled={filtered.length === 0}
          className="flex items-center gap-2 rounded-lg bg-surface px-4 py-2 text-sm hover:bg-surface/80 transition disabled:opacity-40"
        >
          <Download className="h-4 w-4" />
          Export CSV
        </button>
      </div>

      <input
        placeholder="Search by name, email, or external ID..."
        value={search}
        onChange={(e) => setSearch(e.target.value)}
        className="mb-6 w-full rounded-lg border border-border/50 bg-panel px-4 py-2.5 text-sm placeholder:text-text-tertiary focus:outline-none focus:ring-1 focus:ring-info"
      />

      {loading ? (
        <div className="h-64 animate-pulse rounded-2xl border border-border/50 bg-panel" />
      ) : filtered.length === 0 ? (
        <div className="flex flex-col items-center justify-center rounded-2xl border border-dashed border-border/50 bg-panel/20 p-16 text-center">
          <div className="mb-6 flex h-16 w-16 items-center justify-center rounded-2xl bg-info/10">
            <Users className="h-8 w-8 text-info" />
          </div>
          <h2 className="mb-2 text-xl font-semibold">No users yet</h2>
          <p className="max-w-md text-sm text-text-secondary">
            Users appear after completing the SSO exchange flow via a
            workforce IdP app.
          </p>
        </div>
      ) : (
        <div className="overflow-x-auto rounded-2xl border border-border/50 bg-panel">
          <table className="w-full text-sm">
            <thead className="border-b border-border/50 bg-surface/40 text-left text-xs uppercase tracking-wider text-text-tertiary">
              <tr>
                <th className="px-4 py-3">Email</th>
                <th className="px-4 py-3">Name</th>
                <th className="px-4 py-3">External ID</th>
                <th className="px-4 py-3">First Seen</th>
                <th className="px-4 py-3">Last Seen</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-border/30">
              {filtered.map((s) => (
                <tr key={s.id} className="hover:bg-surface/20 transition">
                  <td className="px-4 py-3 font-mono text-xs">{s.email ?? '--'}</td>
                  <td className="px-4 py-3">{s.name ?? '--'}</td>
                  <td className="px-4 py-3 font-mono text-xs text-text-secondary">
                    {s.externalSubject.slice(0, 16)}...
                  </td>
                  <td className="px-4 py-3 text-text-secondary">
                    {new Date(s.firstSeenAt).toLocaleDateString()}
                  </td>
                  <td className="px-4 py-3 text-text-secondary">
                    {new Date(s.lastSeenAt).toLocaleDateString()}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}
