// products/tenantiq/apps/web/src/lib/components/NotificationBell.svelte
<script lang="ts">
	import { Bell, Check, RefreshCw, AlertTriangle, Shield, Database, Info } from 'lucide-svelte';
	import { untrack } from 'svelte';
	import { tenant } from '$stores/tenant';
	import { api } from '$lib/api/client';

	interface Notification {
		id: string;
		type: 'sync' | 'alert' | 'cis' | 'security' | 'info';
		title: string;
		message: string;
		timestamp: string;
		read: boolean;
	}

	let notifications = $state<Notification[]>([]);
	let open = $state(false);
	let loading = $state(false);

	const unreadCount = $derived(notifications.filter(n => !n.read).length);

	const iconMap: Record<string, typeof Bell> = {
		sync: RefreshCw,
		alert: AlertTriangle,
		cis: Shield,
		security: Shield,
		info: Info,
	};

	function relativeTime(ts: string): string {
		const diff = Date.now() - new Date(ts).getTime();
		const mins = Math.floor(diff / 60000);
		if (mins < 1) return 'just now';
		if (mins < 60) return `${mins}m ago`;
		const hrs = Math.floor(mins / 60);
		if (hrs < 24) return `${hrs}h ago`;
		const days = Math.floor(hrs / 24);
		return `${days}d ago`;
	}

	async function fetchNotifications() {
		const tid = $tenant.currentTenantId;
		if (!tid) return;
		try {
			const res = await api.get<{ notifications: Notification[] }>(
				`/tenants/${tid}/notifications`
			);
			notifications = res.notifications;
		} catch { /* silent */ }
	}

	async function markAllRead() {
		const tid = $tenant.currentTenantId;
		if (!tid || unreadCount === 0) return;
		loading = true;
		try {
			await api.post(`/tenants/${tid}/notifications/read-all`);
			for (const n of notifications) n.read = true;
		} catch { /* silent */ }
		loading = false;
	}

	async function markRead(id: string) {
		const tid = $tenant.currentTenantId;
		if (!tid) return;
		const n = notifications.find(x => x.id === id);
		if (!n || n.read) return;
		n.read = true;
		try {
			await api.post(`/tenants/${tid}/notifications/${id}/read`);
		} catch { /* silent */ }
	}

	function togglePanel() {
		open = !open;
		if (open) fetchNotifications();
	}

	function handleClickOutside(e: MouseEvent) {
		const target = e.target as HTMLElement;
		if (!target.closest('.notification-container')) open = false;
	}

	// Fetch on mount and poll every 60s
	$effect(() => {
		if ($tenant.currentTenantId) untrack(() => fetchNotifications());
	});

	$effect(() => {
		const interval = setInterval(fetchNotifications, 60000);
		return () => clearInterval(interval);
	});

	$effect(() => {
		if (open) {
			document.addEventListener('click', handleClickOutside);
			return () => document.removeEventListener('click', handleClickOutside);
		}
	});
</script>

<div class="notification-container relative">
	<button
		type="button"
		onclick={togglePanel}
		class="relative flex h-8 w-8 items-center justify-center rounded-lg text-[var(--color-text-secondary)] transition-colors hover:bg-[var(--color-bg-secondary)] hover:text-[var(--color-text)]"
		aria-label="Notifications"
	>
		<Bell size={16} />
		{#if unreadCount > 0}
			<span class="absolute -right-0.5 -top-0.5 flex h-4 min-w-4 items-center justify-center rounded-full bg-[var(--color-danger)] px-1 text-[10px] font-bold text-white">
				{unreadCount > 9 ? '9+' : unreadCount}
			</span>
		{/if}
	</button>

	{#if open}
		<div class="absolute right-0 top-10 z-50 w-80 max-w-[90vw] animate-fade-up rounded-xl border border-[var(--color-border)] bg-[var(--color-surface)] shadow-lg sm:left-0 sm:right-auto">
			<div class="flex items-center justify-between border-b border-[var(--color-border)] px-4 py-3">
				<h3 class="text-sm font-semibold text-[var(--color-text)]">Notifications</h3>
				{#if unreadCount > 0}
					<button
						type="button"
						onclick={markAllRead}
						disabled={loading}
						class="flex items-center gap-1 text-[11px] font-medium text-[var(--color-primary)] hover:underline disabled:opacity-50"
					>
						<Check size={12} />
						Mark all read
					</button>
				{/if}
			</div>

			<div class="max-h-80 overflow-y-auto">
				{#if notifications.length === 0}
					<div class="px-4 py-8 text-center">
						<Bell size={24} class="mx-auto mb-2 text-[var(--color-text-tertiary)]" />
						<p class="text-xs text-[var(--color-text-tertiary)]">No notifications yet</p>
					</div>
				{:else}
					{#each notifications as n (n.id)}
						{@const Icon = iconMap[n.type] ?? Info}
						<button
							type="button"
							onclick={() => markRead(n.id)}
							class="flex w-full items-start gap-3 px-4 py-3 text-left transition-colors hover:bg-[var(--color-bg-secondary)] {n.read ? 'opacity-60' : ''}"
						>
							<div class="mt-0.5 flex h-7 w-7 shrink-0 items-center justify-center rounded-full {n.read ? 'bg-[var(--color-bg-secondary)]' : 'bg-[var(--color-primary)]/10'}">
								<Icon size={14} class={n.read ? 'text-[var(--color-text-tertiary)]' : 'text-[var(--color-primary)]'} />
							</div>
							<div class="min-w-0 flex-1">
								<div class="flex items-center gap-2">
									<p class="truncate text-xs font-medium text-[var(--color-text)] {n.read ? '' : 'font-semibold'}">{n.title}</p>
									{#if !n.read}
										<span class="h-1.5 w-1.5 shrink-0 rounded-full bg-[var(--color-primary)]"></span>
									{/if}
								</div>
								<p class="mt-0.5 text-[11px] leading-relaxed text-[var(--color-text-secondary)]">{n.message}</p>
								<p class="mt-1 text-[10px] text-[var(--color-text-tertiary)]">{relativeTime(n.timestamp)}</p>
							</div>
						</button>
					{/each}
				{/if}
			</div>
		</div>
	{/if}
</div>

// products/amliq/web/src/components/layout/NotificationBell.tsx
import { useState, useEffect, useRef } from 'react'
import { Bell } from 'lucide-react'
import { api } from '../../api/client'

interface Notification {
  id: string
  action: string
  details: string
  created_at: string
}

export function NotificationBell() {
  const [open, setOpen] = useState(false)
  const [items, setItems] = useState<Notification[]>([])
  const [unread, setUnread] = useState(0)
  const ref = useRef<HTMLDivElement>(null!)

  useEffect(() => {
    fetchNotifications()
    const interval = setInterval(fetchNotifications, 30000)
    return () => clearInterval(interval)
  }, [])

  useEffect(() => {
    const handler = (e: MouseEvent) => {
      if (ref.current && !ref.current.contains(e.target as Node)) setOpen(false)
    }
    document.addEventListener('mousedown', handler)
    return () => document.removeEventListener('mousedown', handler)
  }, [])

  async function fetchNotifications() {
    try {
      const data = await api.get<{ entries: Notification[]; total: number }>('/audit?limit=10')
      setItems(data.entries ?? [])
      setUnread(data.total > 0 ? Math.min(data.total, 9) : 0)
    } catch { /* silent */ }
  }

  return (
    <div ref={ref} className="relative">
      <button onClick={() => { setOpen(!open); setUnread(0) }}
        className="relative w-9 h-9 flex items-center justify-center rounded-xl
          transition-all cursor-pointer active:scale-90"
        style={{ ['--tw-bg-opacity' as string]: 1 }}
        onMouseEnter={e => (e.currentTarget.style.background = 'var(--dash-surface-hover)')}
        onMouseLeave={e => (e.currentTarget.style.background = 'transparent')}>
        <Bell className="w-5 h-5 text-apple-label-secondary" />
        {unread > 0 && (
          <span className="absolute -top-0.5 -right-0.5 w-4 h-4
            bg-gradient-to-br from-red-500 to-rose-600 rounded-full
            text-[10px] text-white flex items-center justify-center font-bold
            shadow-[0_0_8px_rgba(239,68,68,0.5)] animate-pulse">
            {unread}
          </span>
        )}
      </button>

      {open && (
        <div className="absolute right-0 top-11 w-80 max-w-[90vw] rounded-2xl overflow-hidden z-50
          backdrop-blur-xl
          shadow-[0_16px_50px_rgba(0,0,0,0.5)]"
          style={{ background: 'var(--dash-bg-secondary)', border: '0.5px solid var(--dash-border)' }}>
          <div className="px-4 py-3" style={{ borderBottom: '0.5px solid var(--dash-border)' }}>
            <p className="text-sm font-semibold" style={{ color: 'var(--dash-text)' }}>Notifications</p>
          </div>
          <div className="max-h-72 overflow-y-auto">
            {items.length === 0 && (
              <p className="p-6 text-sm text-apple-label-tertiary text-center">
                No notifications
              </p>
            )}
            {items.map(n => <NotifRow key={n.id} item={n} />)}
          </div>
        </div>
      )}
    </div>
  )
}

function NotifRow({ item }: { item: Notification }) {
  const time = new Date(item.created_at).toLocaleString(undefined, {
    month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit',
  })
  return (
    <div className="px-4 py-3 transition-colors cursor-pointer"
      style={{ borderBottom: '0.5px solid var(--dash-border)' }}
      onMouseEnter={e => (e.currentTarget.style.background = 'var(--dash-surface-hover)')}
      onMouseLeave={e => (e.currentTarget.style.background = 'transparent')}>
      <p className="text-sm leading-snug" style={{ color: 'var(--dash-text)' }}>{item.action}</p>
      <p className="text-[11px] text-apple-label-tertiary mt-1">{time}</p>
    </div>
  )
}
